---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deploy
  labels:
    name: wordpress-deploy

spec:
  selector:
    matchLabels:
      name: wordpress-pod
  template:
    metadata:
      name: wordpress-pod
      labels:
        name: wordpress-pod
    spec:
      containers:
      - name: wordpress-container
        image: wordpress:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8085
        #From this point down yet to test.. Lines above running OK locally
        envFrom:
        - configMapRef:
            name: wordpress-cm
        - secretRef:
            name: wordpress-secret





