---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-cm
  labels:
    name: wordpress-cm
data:
  #WORDPRESS_DB_HOST: wordpressdb-svc.bggns.svc.cluster.local
  #WORDPRESS_DB_USER: ...
  #WORDPRESS_DB_NAME: testdb