apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: wpdb-mysql
  labels:
    name: wpdb-mysql

spec:
  replicas: 1
  secretName: wpdb-secret
  persistentVolumeClaim:
    accessModes:
    - ReadWriteOnce
    storageClassName: do-block-storage
    resources:
      request:
        storage: 1Gi
  initFileExtraSQL:
  - "create database mydb"

